### ISSUE TITLE
experiencing great slowdown when using big playlists

### ISSUE THREAD

**Issue by cortegedusage** [michaelherger/Spotty-Plugin#1]
since version 2.8.1 i'm experiencing a great slowdown in 
performance when i'm using a great playlist of 460 numbers.

this is on a raspberry pi v2.

I don't remember having this issues before this version.

I mean slowdown in the web gui, which is how i use it.

**Comment by michaelherger** [comment]
I don’t think this has to do with this version of Spotty, as nothing has changed in that part of the code. Can you elaborate on the extent of the issue? Please enable Info logging for plugin.spotty and provide the server.log file.

**Comment by cortegedusage** [comment]
sorry for the big delay, sometimes real life gets in the way :)
anyway, I've disabled ogg direct playing, and now there is no slowdown anymore.
I'm running picorelayer with lms data on a hdd. At the moment I'm not able to experiment 
a lot. So I'll leave it for what it is for now. Maybe when I get more time in a couple of weeks I'll
investigate further. In the mean time, I just let the music play! 

Thanks

**Comment by michaelherger** [comment]
Thanks for the feedback! You got your priorities right ;-)
