### ISSUE TITLE
Transfer playback - transfer playlist also

### ISSUE THREAD

**Issue by piotrek2555** [michaelherger/Spotty-Plugin#100]
Add Option in transfer playback, transfer also playlist not only song.

**Comment by michaelherger** [comment]
IIRC this is a piece of information we don't get back from the Spotify API. We would only get information about the track being played, sometimes the album it's from, but not whether it's been played as part of a playlist or the album or whatever.

The Transfer feature really was a hack from before I integrated with Connect mode. It's even more limited than the latter. And that won't change.
