### ISSUE TITLE
Playback stops randomly 

### ISSUE THREAD

**Issue by LindyBalboa** [michaelherger/Spotty-Plugin#103]
LMS Version: 8.4.0 - 1676460475 @ Wed 15 Feb 2023 12:55:39 PM CET

Spotty 4.9.1

I have been having the issue of playback stopping randomly, usually after 3 or 4 songs, sometimes after just one. Please find attached the log which I downloaded immediately after a track stopped. By the repeated appearance at the bottom of the file, it looks like an issue with metadata caching/fetching. Please let me know if you need more info.

[server.log](https://github.com/michaelherger/Spotty-Plugin/files/13348192/server.log)

**Comment by michaelherger** [comment]
Please see #82.
