### ISSUE TITLE
Please add firewall open ports in "documentation"

### ISSUE THREAD

**Issue by moltke69** [michaelherger/Spotty-Plugin#112]
Cool plugin (after mysqueezebox.com will be canceled, I want to switch from Deezer to Spotify). Thank you. But it costs me an afternoon until I recognized, that the open port 4070 (beside 80, 443, which is standard) is necessary in the firewall. Thank you.

By the way: Why does the android app or the web player does not need port 4070? They are behind the same firewall.

**Comment by michaelherger** [comment]
Where would you expect the ports to be documented?

**Comment by moltke69** [comment]
Thank you for your question. I can imagine two places:

1. In the README.md in the github repository (https://github.com/michaelherger/Spotty-Plugin). 
2. Just as a remark at the end of the spotty plugin settings page in LMS (http://xx:9000/plugins/Extensions/settings/plugins/Spotty/settings/basic.html). The problem here is, that maybe some others request also some "hints", which would blow up this settings page.
