### ISSUE TITLE
Cannot find the Favorites “playlist”

### ISSUE THREAD

**Issue by AlphaCraft9658** [michaelherger/Spotty-Plugin#118]
Spotify has a dedicated integrated “Favorites” playlist, which I cannot seem to find. Is it somewhere, and I am just not able to find it, or is it not accessible (yet)?

**Comment by michaelherger** [comment]
I'm not sure what you're referring to... What's the exact name of the playlist you're looking for?

**Comment by AlphaCraft9658** [comment]
> I'm not sure what you're referring to... What's the exact name of the playlist you're looking for?

There is the "like" button, which lets you quickly add songs to your favorites. They are displayed as if they were in a playlist, but actually aren't.

**Comment by stripwax** [comment]
.. I don't think everyone would see the same answer to that question....

**Comment by AlphaCraft9658** [comment]
> Is the answer to my question "Lieblingssongs"?

Yes.

**Comment by AlphaCraft9658** [comment]
> > > Is the answer to my question "Lieblingssongs"?
> > 
> > Yes.
> 
> Would have been easier if you had answered the question yourself 😁. 
> 
> Get yourself a client ID (see Settings/Advanced/Spotty), and you should get that list.

Didn't know the exact way it was called in English. Also didn't think I could just say it in German.

**Comment by michaelherger** [comment]
Just answer the question. It's then the asking guy's problem to understand it. As I developed the plugin I have a strings table with all the translations. And I knew/thought you were German 😉.

**Comment by AlphaCraft9658** [comment]
> Just answer the question. It's then the asking guy's problem to understand it. As I developed the plugin I have a strings table with all the translations. And I knew/thought you were German 😉.

You're Swiss, right? Seen that on the forum. So you probably understand German?

**Comment by AlphaCraft9658** [comment]
> > > Is the answer to my question "Lieblingssongs"?
> > 
> > Yes.
> 
> Would have been easier if you had answered the question yourself 😁. 
> 
> Get yourself a client ID (see Settings/Advanced/Spotty), and you should get that list.

It's working now. Can I sort them by "most recently added" though? Right now they are in alphabetical order.

**Comment by michaelherger** [comment]
Try the sorting option in Settings/Advanced/Spotty.
