### ISSUE TITLE
no podcast playback possible

### ISSUE THREAD

**Issue by daniel1v** [michaelherger/Spotty-Plugin#12]
When I try to play podcasts over Spotify Connect, all my players are greyed out. When I use the squeezebox web interface I cannot find any podcasts within spotty.

I have Spotify Premium and playing music works fine. 

Is this a limitation of spotty or may it be another issue / misconfiguration on my sever?

**Comment by michaelherger** [comment]
Yes, there are limitations: for certain platforms I haven't been able to compile new helpers with podcast support. What platform are you running LMS/Spotty on? What spotty helper version are you using (see Settings/Advanced/Spotty)?

**Comment by daniel1v** [comment]
Hi @michaelherger, thank you for the fast reply. 

After some playing around and rebooting it started working.

I am on 
Raspberry Pi 3b+
Raspbian Buster
LMS 7.9.3 - 1586752599
Spotty 4.0.2

Maybe the problem was that the Helper for ARMv8 was activated accidently.
