### ISSUE TITLE
Adding multiple Spotify Account ends up in duplicate accounts

### ISSUE THREAD

**Issue by bbernhard** [michaelherger/Spotty-Plugin#120]
Hi,

I am using your plugin since a few months with a single account and it is working great so far. Thanks a lot for all the work you are doing - it is very much appreciated!

Now I would like to add another Spotify Premium account to Spotty. But unfortunately when I add the second account by logging in with username and password I end up with two duplicate entries in the UI:

![spotty](https://github.com/michaelherger/Spotty-Plugin/assets/5710631/9f9010c1-843d-468c-8382-d7ed82d87e1b)

Although both accounts show up with the exact same name in the Spotty Settings, they are not really identical. In the first Account I see all the playlists that belong to the account. In the second account I do not see and playlists at all (although there should be some). 

Both Spotify Accounts are Premium Accounts which belong to a Family Subscription (although not the same Family subscription). 

I also noticed that there is only one Client Id input field in the Settings. If there are multiple Spotfiy Accounts defined, I would have assumed that the Client Id is per individual account. Or is it supposed to be like that?

Any help is greatly appreciated!

**Comment by michaelherger** [comment]
Please see the description for the client ID: you'll have to add the additional accounts to the client ID configuration (on Spotify's web page).

**Comment by bbernhard** [comment]
Thanks for your fast reply!

Stupid question, but I guess I need to add additional users here, right?

![client_id](https://github.com/michaelherger/Spotty-Plugin/assets/5710631/79caba78-4d1a-4b89-85d6-35f4fbcc067a)

**Comment by bbernhard** [comment]
Just added the user here and it works perfectly fine. :tada:  Thanks a lot for your help - very much appreciated!
