### ISSUE TITLE
Add support for displaying both individual and synchronized players in Spotify Connect

### ISSUE THREAD

**Issue by scholzri** [michaelherger/Spotty-Plugin#125]
**Description:**
First of all, thank you for this amazing plugin! It's been a great addition to my setup.

I have two Squeezelite players named "player1" and "player2" that are made available to Spotify Connect through this plugin. When the players are not synchronized, they both show up as individual devices in the Spotify app, which is great.

However, when I synchronize "player1" and "player2" using the LMS option, the Spotify app only displays "player1 & player2" as a single available device. While this allows me to play audio synchronously on both players via Spotify Connect, it does not show the individual players anymore.

Is there a way to configure the plugin so that it displays both the individual player options ("player1" and "player2") and the synchronized option ("player1 & player2") as available devices in the Spotify app? This would provide more flexibility in choosing whether to play audio on individual players or in a synchronized manner.

**Steps to reproduce:**
Configure "player1" and "player2" to be available to Spotify Connect through the plugin.
Verify that both players show up as individual devices in the Spotify app.
Synchronize "player1" and "player2" using the LMS option.
Observe that only "player1 & player2" shows up as an available device in the Spotify app, while the individual player options are no longer visible.

**Expected behavior:**
When "player1" and "player2" are synchronized, the Spotify app should display the following as available devices:

"player1"
"player2"
"player1 & player2"

This would allow the user to choose between playing audio on individual players or in a synchronized manner.

**Additional information:**
Plugin version: 4.10.1
LMS version: 8.5.2
Spotify app version: 8.9.44.368 / Android 14
Operating system: Home Assistant Operating System 2024.6.0

Please let me know if you need any further information or if there's anything else I can provide to assist in addressing this feature request. Thank you for your time and consideration!

**Comment by michaelherger** [comment]
LMS itself can't address individual players once they're grouped. You'd always control the group.

But as so often there's a 3rd party plugin which might give you what you're looking for: "Group Players". This plugin allows you to play to groups of players without having to synchronise them. So you can have them all separate or grouped, as you like. Please give it a try!

(BTW: that's a LMS "issue", not limited to Spotty)

**Comment by scholzri** [comment]
Thank you very much for the tip. The "Group Players" plugin does an excellent job and completely solves my issue. I'm very happy with it! :)
