### ISSUE TITLE
Quickly cycles through songs wihout playing

### ISSUE THREAD

**Issue by github-username-42** [michaelherger/Spotty-Plugin#126]
When playing songs from any Spotify playlist (initiated from LMS webpage or from player), every song in the playlist is shown on the player (and LMS website) for a split second, then moves on to the next song.  No sound is every played.    If playing a single Spotify song, the song also flashes on the player for a split second, but also does not play.

After uninstalling and reinstalling Spotty, the issue persistted.   On reinstall I could not authenticate via the UI either using the authorize via Spotify player nor via username/password in the GUI.  I was able to authorize via command line.  I also added a Spotify Client ID to setup -- it made no difference.

Spotty was working for a couple of years.  However, it has now been broken for over a month -- not sure when it failed.

Version: 8.4.0 - 1700745578 @ Thu Feb 8 12:16:32 WEST 2024
Operating system: Windows 2012 Server - EN - cp1252
Platform Architecture: 8664
Perl Version: 5.14.1 - MSWin32-x86-multi-thread
Audio::Scan: 1.06
IO::Socket::SSL: 2.068
Database Version: DBD::SQLite 1.58 (sqlite 3.22.0)
Spotty 4.10.1

Spotify account is "Premium Individual"

**Comment by michaelherger** [comment]
Hi there - first of all: update your LMS. 8.4 still tries to use MySqueezebox.com, which has been shut down months ago. I doubt it's the reason for the problem you're seeing, but it can indeed cause some unexpected behaviour. 

Then please make sure you don't have any transcoding customisation enabled in Settings/Advanced/File Formats. You don't use another 3rd party plugin modifying the transcoding pipeline, do you? And also make sure the spotty.exe helper application has access to the internet.

**Comment by github-username-42** [comment]
Updated to 8.5.2, problem persists.

For Spotty Transcoding:
FLAC - spotty.exe/flac
MP3  - spotty.exe/flac
Ogg Vorbis - disabled
PCM - spotty.exe
prefer native format - checked

Disabling PCM causes it to not cycle through all the songs for a split second.  It instead appears ready to play a single song. However, it just sits there going between 0:00 and 0:01 but never moving forward or playing any sound.

spotty -x
ok spotty v1.3.0 - using librespot 0.4.1 c5b689f (Built on 2022-06-04, Build ID: hSvMvEM6, Profile: release)
{"autoplay":true,"debug":false,"lms-auth":true,"ogg-direct":true,"podcasts":true,"save-token":true,"version":"1.3.0","vo
lume-normalisation":true,"zeroconf-port":true}


Spotty can reach the Internet since LMS shows Spotify playlists, songs, etc.  correctly.  It just does not play the song properly anymore.


Moved to:
Version: 8.5.2 - 1716215514 @ Sun May 26 17:38:24 WEDT 2024
Operating system: Windows 2012 Server - EN - cp1252
Platform Architecture: 8664
Perl Version: 5.14.1 - MSWin32-x86-multi-thread
Audio::Scan: 1.08
IO::Socket::SSL: 2.068
Database Version: DBD::SQLite 1.58 (sqlite 3.22.0)
Spotty 4.10.1

**Comment by michaelherger** [comment]
Please note that playback would use a different connection than the other requests to their servers. Therefore really check your firewall whether it's blocking some of spotty.exe's connections.

**Comment by github-username-42** [comment]
Does not appear to be blocked on firewall.   
If I run "spotty.exe -n "Test" -u "zzzzz" -p "yyyy"" and I look at a Spotify Native Client Player running on Mac, Spotty is listed.  So the spotty.exe can reach the Internet.

**Comment by michaelherger** [comment]
If you look at the server.log with debug logging you'll see the command line Spotty is using to play tracks. Try to run one such line (piping the data to /dev/null).

**Comment by github-username-42** [comment]
Sorry, I'm not sure what I should be running.  I tried the following from the debug logs (replacing $URL$)

spotty.exe --ap-port=12321 -n Squeezebox -c "C:\ProgramData\Squeezebox\Cache\spotty\bceac311" --single-track "spotify://track:2yBMVrq96wb9OHbMdBs0lF" --bitrate 96 --disable-discovery --disable-audio-cache --pass-through

No output for above on terminal.   This is Windows, so no /dev/null option, but there doesn't appear to be any output.

**Comment by michaelherger** [comment]
Running that command what would you get? Nothing at all? Would it just exit? Or stay there?

**Comment by github-username-42** [comment]
Turns out a firewall rule "Block unrecognized SSL protocols" was blocking the spotty.exe connection.

**Comment by github-username-42** [comment]
Turns out a firewall rule "Block unrecognized SSL protocols" was blocking the spotty.exe connection.
