### ISSUE TITLE
Spotty on ARMv5 (Synology)

### ISSUE THREAD

**Issue by jr01** [michaelherger/Spotty-Plugin#13]
Hi, 

Here I am back again after a few years with an update on building spotty for ARMv5!

My 2 year old LMS+Spotty setup was broken, probably because of some update to the Synology, and I spent the afternoon on getting Spotty to work again with the latest LMS v8. I couldn't get my old steps, that you have copied to [README.md](https://github.com/michaelherger/Spotty-Plugin/blob/master/Bin/README.md),  working, so I had to restart. In the end it was easy :)

Here are my steps, can you update the README.md ? 

I'm on Ubuntu-20.04 within WSL 2 on Windows.

- Install latest Rust using rustup with the default settings: `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
- Update environment: `source $HOME/.cargo/env`
- Add armv5te target to rust: `rustup target add armv5te-unknown-linux-musleabi`
- Install gcc for arm: `sudo apt install gcc-arm-linux-gnueabi`
- `mkdir ~/.cargo`
- Put the following in `~/.cargo/config`:
```
[target.armv5te-unknown-linux-musleabi]
linker = "arm-linux-gnueabi-gcc"
```
- Get spotty source: `git clone https://github.com/michaelherger/spotty`
- Build: `cargo build --target=armv5te-unknown-linux-musleabi --release`

**Comment by jr01** [comment]
Oh, and Spotify Connect is working perfectly :-)

**Comment by michaelherger** [comment]
Wow!... that was incredibly painless! Thank you VERY much! I'll update the readme.

**Comment by michaelherger** [comment]
That binary is the best build ever: it does not only work on my old Synology NAS, but on piCorePlayer on a Pi3, too. Excellent!

**Comment by jr01** [comment]
Cool!

You just made me test spotty on a Pi-zero W.... and there it runs also!! Although I must confess that I have no audio device connected, but `./spotty -u *** -p ***  --single-track spotify:track:***** -n /dev/null` showed it's playing.

**Comment by michaelherger** [comment]
Awesome! What OS are you running on that Pi0?

**Comment by jr01** [comment]
Raspbian Buster Lite
