### ISSUE TITLE
Feature: Spotify device for multiple players

### ISSUE THREAD

**Issue by NathanSweet** [michaelherger/Spotty-Plugin#132]
I would like to define a Spotify device that is multiple LMS players. That would allow me to have eg `Kitchen`, `Living Room`, and `Kitchen+Living Room` Spotify devices. Do you think this is technically feasible? Are you interested in adding such a feature? I'd be happy to donate some funds to help it happen!

AFAICT, LMS has a feature to synchronize multiple players, but this does not do what I want. I want both individual players and the ability to have a “composite” player that synchronizes multiple players. The LMS synchronize feature permanently syncs the players, ruining individual use.

**Comment by michaelherger** [comment]
There's the "Group Player" plugin to do this. Give it a try!

**Comment by NathanSweet** [comment]
Super cool, thank you!!
