### ISSUE TITLE
[Feature Request] Volume Level Option

### ISSUE THREAD

**Issue by Hypfer** [michaelherger/Spotty-Plugin#15]
The official spotify client provides a volume level option, which seems to actually fetch the tracks with a different volume level and not simply process them locally.

It looks like this:
![image](https://user-images.githubusercontent.com/974410/84006134-87ea5700-a96e-11ea-95a8-aeb1d7ac86a6.png)

When using Spotty in combination with local music which has been mp3gained to 89dB it's overall not a very pleasant experience. The "replay gain" LMS feature also doesn't really help here it seems.

Therefore I think that this would be a great addition to the plugin

**Comment by michaelherger** [comment]
What makes you think it's using different files? That would very much surprise me.

Did you see the per-player Spotty setting to enable Spotify's replay gain?

**Comment by Hypfer** [comment]
I was assuming that that's the case since these settings would only be applied when playing new and therefore (assumed) non-cached songs. I guess that was wrong then

Oh! Nope. Never saw that option before. That should be the solution

Thanks!

**Comment by Hypfer** [comment]
Nope. Everything is still loud. What does the option do exactly?

https://github.com/librespot-org/librespot/blob/ef27b4bce371d0a41e7ee2263244ed141684ff9b/playback/src/config.rs#L41

I saw that you can specify a pregain value. Maybe the replay gain feature gains to a value higher than 89dB?
That would be easy to make it configurable I suppose

**Comment by Hypfer** [comment]
https://github.com/dtcooper/raspotify/issues/151#issuecomment-621658452

This is also interesting 🤔

**Comment by michaelherger** [comment]
TBH I've never used the various replay gain options available. There are many combinations of RG for local files, remote files, Spotty...

**Comment by mavit** [comment]
> The official spotify client provides a volume level option, which seems to actually fetch the tracks with a different volume level and not simply process them locally.

Spotify's Mastering and Loudness FAQ [explains](https://artists.spotify.com/faq/mastering-and-loudness#can-users-adjust-the-levels-of-my-music) what those options do in the official client.

> The "replay gain" LMS feature also doesn't really help here it seems.

I'm grateful to tw99 who [pointed out](https://forums.slimdevices.com/showthread.php?112390-Spotty-with-ReplayGain&p=978412&viewfull=1#post978412) on the Slim Devices Forum that ReplayGain works with Spotty if one disables the Spotty to Ogg Vorbis helper.

After some experimentation, I discovered ReplayGain works with Spotty also if playing to a group of synced players.

I tried changing direct for proxied streaming, but that made no difference.

> Did you see the per-player Spotty setting to enable Spotify's replay gain?

Is it helpful for this option to exist?  Isn't it enough to have the ReplayGain option in Settings -> Player -> Audio?

**Comment by michaelherger** [comment]
Are you saying that
* not using Ogg direct
* enabling ReplayGain outside the Spotty plugin
* disabling normalisation in Spotty
would work as expected?

**Comment by mavit** [comment]
Sorry, no, I drifted off topic at the end, there.  I’ve raised issue #16 to focus on the latter issue.

My observation was that ReplayGain worked if I:
- Enabled “Settings → Player → Audio → Volume Adjustment/Replay Gain” (I didn’t test with this disabled).
- And enabled “Settings → Player → Spotty Spotify for Squeezebox → Volume Adjustment/Replay Gain” (I didn’t test with this disabled).
- And played Spotify to a group of synced players.

ReplayGain also worked if I:
- Enabled “Settings → Player → Audio → Volume Adjustment/Replay Gain” (I didn’t test with this disabled).
- And enabled “Settings → Player → Spotty Spotify for Squeezebox → Volume Adjustment/Replay Gain” (I didn’t test with this disabled).
- And disabled the Spotty to Ogg Vorbis helper in “Settings → Advanced → File Types”

ReplayGain did not work if I:
- Enabled “Settings → Player → Audio → Volume Adjustment/Replay Gain” (I didn’t test with this disabled).
- And enabled “Settings → Player → Spotty Spotify for Squeezebox → Volume Adjustment/Replay Gain” (I didn’t test with this disabled).
- And enabled the Spotty to Ogg Vorbis helper in “Settings → Advanced → File Types”.
- And enabled “Settings → Player → Audio → Streaming Method → Proxied Streaming”.
- And played to a single unsynced player.

Hope that clears up what I was trying to say.

**Comment by michaelherger** [comment]
@Hypfer can you confirm that @mavit's settings would work for you too?

**Comment by Hypfer** [comment]
Sadly no.

I've disabled the Ogg Vorbis helper and confirmed that tracks are in fact transcoded to FLAC.
Player replay gain is set to Track normalization and Spotty volume adjustment is enabled.

Spotify is still a lot louder :(

**Comment by Hypfer** [comment]
Actually it does work when playing to a manually-created group.

Previously I tried using a dynamic group of players created by the player groups plugin which apparently is handled as a single player?

Why the difference between single players and groups?

**Comment by michaelherger** [comment]
That's a good question. Maybe one to ask @philippe44?

**Comment by philippe44** [comment]
There is a difference about volume synchronization. With manually synchronized player, if you change the volume of one player, all players with the "sync volume" enabled will change accordingly. When they are part of a Group player, the change of volume of one does not change the others, regardless of "sync volume setting". Other than that, the transcoding rule can be different as in a manual group, I think the rule is the first one that fits the master and all slaves. In a Group player, the master has no codec, so the 1st slave "guides".

**Comment by slartibartfast3** [comment]
I tried the settings suggested my @mavit, disabling ogg vorbis for Spotty plays back at a lower volume than with it enabled. @michaelherger  have you tried this yourself? I still think if Spotify replaygain is purely based on track gain then it isn't worth using.

**Comment by michaelherger** [comment]
Unfortunately the librespot community has refused to accept the Ogg direct patch @philippe44 had sponsored. And it's becoming increasingly difficult to maintain it along with the upstream changes. Therefore the Ogg direct streaming mode might be a thing of the past all too soon.

I personally don't use volume normalisation.

**Comment by mavit** [comment]
> ReplayGain also worked if I:
> 
> * Enabled “Settings → Player → Audio → Volume Adjustment/Replay Gain” (I didn’t test with this disabled).
> 
> * And enabled “Settings → Player → Spotty Spotify for Squeezebox → Volume Adjustment/Replay Gain” (I didn’t test with this disabled).
> 
> * And disabled the Spotty to Ogg Vorbis helper in “Settings → Advanced → File Types”

I’ve done a bit more reading and think I now understand why this is.

- The `--enable-volume-normalisation` option means “apply volume normalisation within `librespot` to the decoded PCM”.  Hence, it doesn’t do anything when Ogg output is used.
- [Spotify communicates what gain to use via its own special header rather than the tags generated by `vorbiscomment`](https://github.com/librespot-org/librespot/pull/162#issuecomment-368114997).  Hence, when `spotty` outputs Ogg, LMS won’t be able to apply volume normalisation itself.

**Comment by Hypfer** [comment]
I honestly forgot that there was an issue.

With the spotty ogg file type disabled it seems to still work with a manually created player group which is likely all I've been using since I've reported this.
Currently, I'm running spotty 4.6.2 with lms 8.2.0 in docker

For some reason, I can't even enable vorbis as it is greyed out
![image](https://user-images.githubusercontent.com/974410/145457696-07773093-2f31-4779-88b9-cefd5999cafd.png)


I've been a happy user of spotty in the last year so I guess this can be closed
