### ISSUE TITLE
Can't installed Spotty plugin anymore

### ISSUE THREAD

**Issue by phqzgunsfjror** [michaelherger/Spotty-Plugin#155]
Hi Michael,

for some reason I cannot install the Spotty plugin anymore. I selected the Spotty plugin, clicked on "Save Settings", then it wants to restart but nothing happens (I also waited for a long time). If I refresh the page, the Spotty plugin looks like it is not installed and I could do this procedure again.

I am using a Raspberry Pi 4. Previously I had logitechmediaserver installed and purged it with:
```
sudo dpkg --purge logitechmediaserver
sudo rm -rf /var/lib/squeezeboxserver
```

Then I installed lyrionmusicserver with:
```
sudo apt install ./lyrionmusicserver_9.0.0_arm.deb
```

I have the feeling the prev. installation is the reason.
Btw: I tested it with a fresh Raspbian and there it works like a charm but I don't wanna reinstall everything since I have also other software like smarthome installed.

Am I missing something? Do you have advice for me?

**Comment by michaelherger** [comment]
I think you're seeing https://github.com/LMS-Community/slimserver/issues/1242: the restart prompt is shown before the plugin has been downloaded. 

Please give the latest 9.0.1 nightly build a try (https://lyrion.org/downloads/#v901-stable-nightly-build). It should fix that behaviour.

**Comment by phqzgunsfjror** [comment]
@michaelherger thank you very much! Indeed, it fixed it.
