### ISSUE TITLE
The spotify connect don't work

### ISSUE THREAD

**Issue by marcbrunet92** [michaelherger/Spotty-Plugin#156]
The spotify connect feature doesn't run.
Lyrion Music Server Version : 9.0.0 - 1732822968 @ Fri Nov 29 12:08:33 UTC 2024
Nom d'hôte : raspberrypi
IP : 192.168.0.35
Port HTTP : 9000
SE : Debian - FR - utf8
Plate-forme : aarch64-linux
Version de la base de données : SQLite
Platines identifiées : 7
Squeezeox boom

**Comment by marcbrunet92** [comment]
Spotty v4,11.140
![Screenshot_20241212_073940_Chrome.jpg](https://github.com/user-attachments/assets/db4436f0-06f9-49d3-8eeb-eba433b35b38)

**Comment by michaelherger** [comment]
The test version doesn't have Connect support. I try to mention this wherever I post the link.

**Comment by michaelherger** [comment]
BTW: why would some of the text there be so big?

**Comment by marcbrunet92** [comment]
J'ai fait un zoom

Le jeu. 12 déc. 2024, 07:48, Michael Herger ***@***.***> a
écrit :
