### ISSUE TITLE
[Feature Request] Search support for Spotify URIs

### ISSUE THREAD

**Issue by Hypfer** [michaelherger/Spotty-Plugin#17]
Currently, it's not possible to paste a spotify URI into the search bar to get the Track/Album/Playlist.

Example: `spotify:track:3AVZudpwC1DkkYJH65OGC4`

![image](https://user-images.githubusercontent.com/974410/88372901-1c7e0c80-cd97-11ea-8f66-d21248d79ae4.png)

If searched by name and added to the playlist, the track ID from the URI can be found in the info section:
![image](https://user-images.githubusercontent.com/974410/88372976-48998d80-cd97-11ea-95ab-128d690dff85.png)

**Comment by Hypfer** [comment]
If I understand
https://github.com/librespot-org/librespot/blob/551daadc44a39336e1c643d1e300d38cdd8426d5/protocol/proto/search.proto#L3-L19

correctly, it should be sufficient to change this

https://github.com/michaelherger/Spotty-Plugin/blob/98e7907e8b7307097ee9daa100c0929160e94db3/API.pm#L379

so that it writes the `q` value to `spotify_uri` if `q` starts with `spotify:`

**Comment by michaelherger** [comment]
Thanks for the hint! Until I get back to working on stuff... you can paste that link in to the "Tune In to..." input field in the Radios section, or the '+' button in the Material skin.

**Comment by michaelherger** [comment]
> If I understand
> https://github.com/librespot-org/librespot/blob/551daadc44a39336e1c643d1e300d38cdd8426d5/protocol/proto/search.proto#L3-L19
> 
> correctly, it should be sufficient to change this
> 
> https://github.com/michaelherger/Spotty-Plugin/blob/98e7907e8b7307097ee9daa100c0929160e94db3/API.pm#L379
> 
> so that it writes the `q` value to `spotify_uri` if `q` starts with `spotify:`

I'm using the [web UI](https://developer.spotify.com/console/get-search-item/) for anything but playback and Connect mode. The web search would not support searching for IDs. 

But then there's enough information in a URI to know what type of information we'd be looking for. I wouldn't have to implement this on an API interaction level, but in the plugin code. Eg. if I recognise a URI, then don't search, but look up that item directly.

**Comment by michaelherger** [comment]
Oh... I actually have this implemented already for URIs covering playlists, albums, artists, podcast shows... but not tracks! Shouldn't be too hard to add :-)

**Comment by michaelherger** [comment]
Fixed in commit b69565a

**Comment by Hypfer** [comment]
Thanks!
