### ISSUE TITLE
Synology Diskstation 218 - ldd is missing

### ISSUE THREAD

**Issue by MartinMuzatko** [michaelherger/Spotty-Plugin#2]
Hello!

I have trouble getting spotty to run for LMS on Synology.

## Error Message

This is what I get in the settings page of the plugin.
```
There has been a problem running the Spotty helper application. Most likely your operating system and/or platform is not supported. Please report the following details to me:

Operating system: Synology DiskStation / unknown

Helper Applications Folder:
Information is not avaialable. Please update Logitech Media Server to 7.7.6 or more recent.
sh: ldd: command not found
```

So I tried to get ldd (which is a command from glibc/glibc-common. But for the life of me, I couldn't find a deb package to install using dpkg. (Synology uses a custom linux with proprietary package managers only)

ok, so I tried to search for solutions online:

I have located the plugin folder and tried to follow the instructions as described here:
https://forums.slimdevices.com/showthread.php?110455-Announce-Spotty-2-8-x-Spotify-Connect-for-your-Squeezebox
Downloading and moving the spotty-custom to `/volume1/@appstore/SqueezeCenter/Cache/InstalledPlugins/Plugins/Spotty/Bin#` did not help :( (I restarted LMS and then the NAS after this action).

## Additional info:

uname -a
`Linux Bastet 4.4.59+ #23824 SMP Tue Feb 12 16:50:48 CST 2019 aarch64 GNU/Linux synology_rtd1296_ds218`

cat /proc/cpuinfo
```
cat /proc/cpuinfo  
processor       : 0
model name      : ARMv8 Processor rev 4 (v8l)
BogoMIPS        : 54.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4
```

Thank you in advance!

**Comment by michaelherger** [comment]
Please install the additional "Spotty Helper Application for ARMv8" plugin.

**Comment by michaelherger** [comment]
What would `perl -v` give you?

**Comment by MartinMuzatko** [comment]
Today I had time for further setting up my NAS. And it works!
Wouldn't have thought that I would need a second plugin :D but makes sense now that I read it.

Thank you so much.
Servus und Baba.

**Comment by michaelherger** [comment]
Thanks for the feedback. I do not include the "more exotic" helpers, as they would add considerable overhead to the plugin package which 99% of the users wouldn't need anyway. Ok, it's probably 98%, but anyway 😄.
