### ISSUE TITLE
Installing on LMS 8.0 on Mac OSX?

### ISSUE THREAD

**Issue by rossgrady** [michaelherger/Spotty-Plugin#20]
OK, I cloned this repo into /Library/PreferencePanes/Squeezebox.prefPane/Contents/server/Slim/Plugin/Spotty & it shows up as an installed plugin in the settings UI, but the name is `SPOTTY_PLUGIN_NAME` and there is no settings link in the right hand column, and then sure enough when I look at the logs I see
```
Slim::Display::Display::string (887) Error: missing string PLUGIN_SPOTTY_NAME
```

So I guess there is at least one additional step I need to perform in order for everything to be happy?

**Comment by michaelherger** [comment]
That’s the wrong folder. There’s even a readme in Plugin telling you so 😉. See `Settings/Information` for where you’ll find the `Plugins` (with an S) folder. Put the plug-in there.

**Comment by rossgrady** [comment]
This is what I have in `Settings/Information`: 

/Users/ragrady/Library/Caches/Squeezebox/InstalledPlugins/Plugins, /Users/ragrady/Library/Application Support/Squeezebox/Plugins, /Library/Application Support/Squeezebox/Plugins, /Library/PreferencePanes/Squeezebox.prefPane/Contents/server/Plugins

I tried ` /Users/ragrady/Library/Application Support/Squeezebox/Plugins` and `/Library/PreferencePanes/Squeezebox.prefPane/Contents/server/Plugins` and in both cases I get basically the same error emitted:

```
[20-09-29 15:18:35.7255] Slim::Display::Display::string (887) Error: missing string PLUGIN_SPOTTY_NAME
[20-09-29 15:18:35.7259] Slim::Display::Display::string (887) Backtrace:

   frame 0: Slim::Utils::Log::logBacktrace (/Library/PreferencePanes/Squeezebox.prefPane/Contents/server/Slim/Display/Display.pm line 887)
   frame 1: Slim::Display::Display::string (/Library/PreferencePanes/Squeezebox.prefPane/Contents/server/Slim/Player/Player.pm line 193)
   frame 2: Slim::Player::Player::string (/Library/PreferencePanes/Squeezebox.prefPane/Contents/server/Slim/Utils/Strings.pm line 544)
   frame 3: Slim::Utils::Strings::clientString (/Library/PreferencePanes/Squeezebox.prefPane/Contents/server/Slim/Menu/SystemInfo.pm line 439)
   frame 4: Slim::Menu::SystemInfo::infoPlugins (/Library/PreferencePanes/Squeezebox.prefPane/Contents/server/Slim/Menu/Base.pm line 170)
   frame 5: (eval) (/Library/PreferencePanes/Squeezebox.prefPane/Contents/server/Slim/Menu/Base.pm line 170)
   frame 6: Slim::Menu::Base::addItem (/Library/PreferencePanes/Squeezebox.prefPane/Contents/server/Slim/Menu/Base.pm line 140)
   frame 7: Slim::Menu::Base::menu (/Library/PreferencePanes/Squeezebox.prefPane/Contents/server/Slim/Web/Settings/Server/Status.pm line 31)
   frame 8: Slim::Web::Settings::Server::Status::handler (/Library/PreferencePanes/Squeezebox.prefPane/Contents/server/Slim/Web/HTTP.pm line 1155)
   frame 9: Slim::Web::HTTP::generateHTTPResponse (/Library/PreferencePanes/Squeezebox.prefPane/Contents/server/Slim/Web/HTTP.pm line 912)
   frame 10: Slim::Web::HTTP::processURL (/Library/PreferencePanes/Squeezebox.prefPane/Contents/server/Slim/Web/HTTP.pm line 707)
   frame 11: Slim::Web::HTTP::processHTTP (/Library/PreferencePanes/Squeezebox.prefPane/Contents/server/Slim/Networking/IO/Select.pm line 122)
   frame 12: (eval) (/Library/PreferencePanes/Squeezebox.prefPane/Contents/server/Slim/Networking/IO/Select.pm line 118)
   frame 13: Slim::Networking::IO::Select::__ANON__ (/Library/PreferencePanes/Squeezebox.prefPane/Contents/server/Slim/Networking/IO/Select.pm line 167)
   frame 14: (eval) (/Library/PreferencePanes/Squeezebox.prefPane/Contents/server/Slim/Networking/IO/Select.pm line 167)
   frame 15: Slim::Networking::IO::Select::loop (./slimserver.pl line 728)
   frame 16: main::idle (./slimserver.pl line 678)
   frame 17: main::main (./slimserver.pl line 1211)
```

This is a clean clone of Public/8.0 from last night, running on High Sierra. 

The one thing I don't know is how old the PreferencePane itself is -- it shows Version 7.7.5 at the bottom. I either can't figure out, or have forgotten, how to find the most recent PreferencePane code for MacOS.

**Comment by michaelherger** [comment]
Why don't you just install Spotty using the plugin manager?...

**Comment by rossgrady** [comment]
Maybe because I'm also having this error in LMS, whoops: 

```
[20-09-29 15:52:12.5960] Slim::Networking::Repositories::__ANON__ (147) Failed to fetch https://repos.squeezecommunity.org/extensions.xml: Connect timed out: 
[20-09-29 15:52:27.4470] Slim::Networking::Repositories::__ANON__ (147) Failed to fetch https://repos.squeezecommunity.org/extensions.xml: Connect timed out: Bad file descriptor
```

Seems like I should focus on solving that problem :)

I can load it in my web browser, but for some reason the Public/8.0 clone I did yesterday seems to be struggling with it. Any thoughts (since that's your project too)?

**Comment by michaelherger** [comment]
What macOS version is this? You might be using an outdated IO::Socket::SSL version (which happens on 10.13 or older, IIRC). See eg. https://forums.slimdevices.com/showthread.php?109738-Error-Can-t-connect-to-remote-server-to-retrieve%85&p=925539&viewfull=1#post925539 for instructions about how to update the libraries. Catalina should not require this update.

**Comment by rossgrady** [comment]
Yep, that's likely it. I just checked and it's . . . gulp . . . El Cap. It's on a ~2009 Mac Mini which is otherwise basically perfect as a media server. 

I was getting ready to poke at OpenSSL so I'll check out those docs. Thanks!!

**Comment by rossgrady** [comment]
That did it!
