### ISSUE TITLE
Getting "Timeout waiting for a token" after some time of running Logitech Media Server with spotty plugin

### ISSUE THREAD

**Issue by chrismuller** [michaelherger/Spotty-Plugin#21]
When I newly start Logitech Media Server, the spotty plugin works fine. After some time (a few hours max), however, the spotty plugin is no longer working and the log shows "Timeout waiting for a token".

Once I reboot my raspberrypi, the spotty plugin runs again fine (for some time).

I am running Logitech Media Server on raspberrypi:

Logitech Media Server Version: 7.9.3 - 1597753178 @ Sun Aug 23 19:23:14 CEST 2020
Hostname: raspberrypi
IP: 192.168.2.4
HTTP-Port: 9000
BS: Debian - DE - utf8
Plattform: armv8l-linux
Perl-Version: 5.20.2 - arm-linux-gnueabihf-thread-multi-64int
Audio::Scan: 0.95
IO::Socket::SSL: 2.002
Database version: DBD::SQLite 1.58 (sqlite 3.22.0)

**Comment by michaelherger** [comment]
I'm running two LMS instances on Pi, one using pCP, one Raspberry OS myself. This should just work. What OS are you using?

**Comment by chrismuller** [comment]
OS is Raspberry Pi OS.

I did some further digging and discovered that this must actually be a network issue in my LAN with the raspberrypi losing IPv6 connectivity after some time. Spotty tries to use IPv6 and times out (rather than defaulting back to IPv4). So, not really spotty's fault.

Anyway, many thanks for your quick answer and all the great work!

Best,

**Comment by michaelherger** [comment]
Thanks for the feedback!
