### ISSUE TITLE
Unable to see or use any playlist

### ISSUE THREAD

**Issue by TerryDieckmann** [michaelherger/Spotty-Plugin#23]
Since a week or so, I am not able to see my own playlists or playlists created by other users. Albums still work though. I have updated to the last version today (v4.4.2), but it is still broken.

All playlists show up, but are empty and cannot be played or added to the current selection.

![image](https://user-images.githubusercontent.com/18029728/99548033-82327c00-29b8-11eb-9c92-ca170a517ebb.png)

**Comment by michaelherger** [comment]
If you only updated today, then you're likely seeing cached results from before. 4.4.3 was release to fix this particular issue. 

You could shut down LMS, delete cache.db from LMS' cache folder, then try again.

**Comment by TerryDieckmann** [comment]
> If you only updated today, then you're likely seeing cached results from before. Spotty v4.4.3 was released yesterday to fix this particular issue.
> 
> You could shut down LMS, delete cache.db from LMS' cache folder, then try again.

I do not have a cache.db file in the LMS directory for some reason. Also, my plugins page does not see the new v4.4.3 version... Gotta love LMS

**Comment by michaelherger** [comment]
What are you running your LMS on? What folder did you check to find cache.db?

**Comment by TerryDieckmann** [comment]
I'm running LMS on my own Windows 10 PC (10.0.17763) and I checked the folder which contains the LMS control panel executable. I just checked my plugins page and now it shows that there is an update for Spotty.. 4.4.4? I just installed it and now it's working 👍 

![image](https://user-images.githubusercontent.com/18029728/99634399-b9e50680-2a40-11eb-8bae-0d76055a1cfe.png)
