### ISSUE TITLE
Playlist Transfer is only possible when Spotify Connect is enabled

### ISSUE THREAD

**Issue by Gagi2k** [michaelherger/Spotty-Plugin#24]
When the following option is checked in the Spotty settings:

Don't announce Squeezebox players running in Spotify Connect mode in your network. Check this option if you don't want your Spotify Connect enabled Squeezebox player to show up in all Spotify apps in your network.  

The Playlist Transfer option doesn't do anything. If Spotify Connect needs to be enabled for this feature to work, it might make sense to hide the option if it is not enabled.

**Comment by michaelherger** [comment]
I'm not sure I understand: would the Transfer... item not show any clients? Where and where from do you want to transfer?

Please note that this feature is mostly from pre-connect days. It's used to try to move a connect controlled playlist to LMS.

**Comment by Gagi2k** [comment]
If Spotify Connect is disabled in settings, the Transfer... shows my devices which are currently playing, but when pressing on those it doesn't work and i also don't get any error for it (atleast not in the UI).

If i turn on Spotify Connect, the Transfer works as expected. So my assumption was that the Transfer can only work if Spotify Connect is turned on, so it would make sense to show an error text (or hide all clients all the time) in this case in the Transfer... menu.

I really like the feature, it's really convenient as i don't need to open my phone to do the transfer, but just use the tablet which shows the LMS controls anyway.

**Comment by michaelherger** [comment]
> If Spotify Connect is disabled in settings, the Transfer... shows my devices which are currently playing, but when pressing on those it doesn't work and i also don't get any error for it (atleast not in the UI).

"my devices" - are these other Spotify Connect speakers, NOT a Squeezebox or the like?

**Comment by michaelherger** [comment]
Ok, to come back to the initial question: transfer should work in both cases. But they'd work in different ways. When Connect is enabled, your Spotify Connect control switches to using your Spotty based player, but is still in Connect mode.

When Connect is disabled, Spotty would try to get the context from the current player and transfer control over to LMS/Spotty. Unfortunately Spotify would often not give enough information about the currently playing context (album, playlist, radio...) to successfully reproduce the state in LMS. You can turn on debug logging for `plugin.spotty` to see what it tries to do (or send me the server.log.zip for inspection).

**Comment by Gagi2k** [comment]
ok, thx, i will give it a try an will come back to you.

Although i like spotify connect in general, what i dislike is that only one track is shown in the LMS playlist (which i guess is how spotify connect works). So if the other approach would do a real copy of the current playlist, i probably would like this approach more (if it works reliable) and would love to have a way to use this transfer, while still having the option to initiate a spotify connect from my phone using the Spotify app.

**Comment by michaelherger** [comment]
> Although i like spotify connect in general, what i dislike is that only one track is shown in the LMS playlist (which i guess is how spotify connect works). So if the other approach would do a real copy of the current playlist, i probably would like this approach more (if it works reliable) and would love to have a way to use this transfer, while still having the option to initiate a spotify connect from my phone using the Spotify app.

That's exactly the problem with this kind of transfer: Spotify would often _not_ give us enough context to replicate the playback :(

**Comment by michaelherger** [comment]
This is not going to be fixed.
