### ISSUE TITLE
Spotty doesn't provide a URL when used by LMS CLI commands

### ISSUE THREAD

**Issue by Gagi2k** [michaelherger/Spotty-Plugin#25]
Using the following query for getting all "What's new" playlist, doesn't list the URLs for the respective playlists.

`spotty items 0 100 want_url:1 item_id:1`

Similar using the query for listing the tracks in the first playlist also doesn't show the URL for the tracks:

`spotty items 0 100 want_url:1 item_id:1.1`

**Comment by michaelherger** [comment]
Why would you want to get the URL for one of those menu items? I believe that while you might indeed unearth a few bugs, you're approaching your implementation the wrong way 😃. What are you trying to do? I believe you should either use the menus as we provide them, not fiddling with what they represent. Or do it all yourself, without the need to understand what the menu as shipped by LMS would represent.

**Comment by Gagi2k** [comment]
I'm forwarding the menu items one to one to the user and you are right for this, i don't need to know the URL of the items.

But i would also like to let the user save an album or playlist to the LMS favorites similar to the LMS Web-UI. For this i also need to have an url to save. It doesn't need to be a real spotify URL, just something i can save in the favorite list and can be used to start playing this album/playlist

**Comment by michaelherger** [comment]
How do you get the menus? There should be a `favorite_url` or similar property giving you the "raw" URL to use for this very use case.

**Comment by Gagi2k** [comment]
Hi,

yes with menu:1 i'm getting what i was searching for, thx.
