### ISSUE TITLE
Bitrate selection from the Settings page in LMS is not used by the plugin

### ISSUE THREAD

**Issue by hansherlighed** [michaelherger/Spotty-Plugin#27]
Looking through the code while trying to find a solution to specifying a static listening port, I noticed that the bitrate seems to be hardcoded in Daemon.pm

On line 67 in Daemon.pm you have this:
```
	my @helperArgs = (
		'-c', $self->cache,
		'-n', $self->name,
		'--disable-audio-cache',
		'--bitrate', 96,
		'--player-mac', $self->mac,
		'--lms', Slim::Utils::Network::serverAddr() . ':' . preferences('server')->get('httpport'),
	);
```

Shouldn't that be:
```
	my @helperArgs = (
		'-c', $self->cache,
		'-n', $self->name,
		'--disable-audio-cache',
		'--bitrate', $prefs->get('bitrate'),
		'--player-mac', $self->mac,
		'--lms', Slim::Utils::Network::serverAddr() . ':' . preferences('server')->get('httpport'),
	);
```

I'm no expert, so please forgive me if I'm wrong.

**Comment by michaelherger** [comment]
Don't worry: the actual streaming connection will use whatever you selected. What you're seeing here is the Connect control daemon.

I'm sorry for the delay on your other issue. I need more time to look into that one.
