### ISSUE TITLE
Account Rate Limiting makes use of spotify (multi account) difficult

### ISSUE THREAD

**Issue by droid-user** [michaelherger/Spotty-Plugin#28]
In the last few weeks, spotify seems to have added restrictive rate limitings. I constantly run into problems selecting/finding music, as loading the spotty app fails due to missing access tokens, browsing album lists works only after trying for several times before something is displayed etc.

My setup:
- raspPi running the logitech media server
- 5 Radios connected to play music (3 Logitech Radios, 1 Raspi running the server, 1 extra)
- 4 Spotify accounts connected in the spotty app (all within a family account)

I followed the suggestion to create a spotify client ID, but that didn't help

Some of the example errors in the radio-display or the spotty-settings (non-exhaustive):

- Konnte keinen Access Token erhalten
- Zugriffsrate überschritten für: me/albums?limit=50&offset=250; nächster Versuch in 8 Sekunden
- Zugriffsrate überschritten für: me/player/devices; nächster Versuch in 16 Sekunden.

My setup worked like an absolute charm for the last years (thanks allot for the brilliant work). Is spotify going into a direction of making such things impossible, or is there a way to fix this for spotty and LMS?

Greets, fred

**Comment by michaelherger** [comment]
After you configured the client ID, did you give the system at least an hour to settle? I believe there still is an issue with cached tokens which would only expire after about an hour. Thus it might take longer for the client ID to take effect than expected.

**Comment by droid-user** [comment]
> 
> 
> After you configured the client ID, did you give the system at least an hour to settle? I believe there still is an issue with cached tokens which would only expire after about an hour. Thus it might take longer for the client ID to take effect than expected.

You got me :) I played with the new client-ID for the last half hour before writing that bug-report.

I will give it some time to rest and will report back.

Still I hope that this is not the beginning of "the end" of spotify allowing use-cases like this... I love that set-up and haven't seen an adequate alternative

**Comment by michaelherger** [comment]
I don't think it's a targeted action against Spotty: the number of Spotty users still is growing every month. Add to this the new library integration, which creates additional traffic. We simply crossed a threshold of daily/hourly/whatever time unit requests which they consider too much without a commercial agreement. And we're talking about a considerable number of requests (millions/day), which probably is legitimate.

**Comment by droid-user** [comment]
Gave it a few hours now and it works with the Client-ID! So no bug, but only me being impatient :)

So solution is: Follow the provided info within the spotty settings on how to resolve this by getting a developer's account and a client id for an example app

**Comment by droid-user** [comment]
> I don't think it's a targeted action against Spotty: the number of Spotty users still is growing every month. Add to this the new library integration, which creates additional traffic. We simply crossed a threshold of daily/hourly/whatever time unit requests which they consider too much without a commercial agreement. And we're talking about a considerable number of requests (millions/day), which probably is legitimate.

You're probably right, i didn't actually mean it as an accusation agains Spotify, just as the fear, that alternative non-commercial use cases might just be too much of a struggle for them to bother any more. But on the other hand, that's what the api is made for, so you are right! Thanks again for this plugin!
