### ISSUE TITLE
CLI with playlist link doesnt work

### ISSUE THREAD

**Issue by felixschrouff** [michaelherger/Spotty-Plugin#3]
Hi Michael,

I'm tring to change playlists with my ioBroker instance with the "pathURL" attribute but that doesnt work.

![image](https://user-images.githubusercontent.com/20982567/62049261-1f3f3380-b20f-11e9-8649-2dfe29af687a.png)

then i tried to change the playlist with the CLI that also didnt work. I used: playlist play spotify://playlist:<id>

what I'm doing wrong?

**Comment by michaelherger** [comment]
Use Spotify's URI, rather than the version with the two dashes:

`playlist play spotify:playlist:37i9dQZF1CA9IpeAkgMC6h`

**Comment by felixschrouff** [comment]
perfect, thank you.

Problem solved
