### ISSUE TITLE
Spotty don't show Albums in -> Artists -> Artist-Name ->....

### ISSUE THREAD

**Issue by hismastersvoice** [michaelherger/Spotty-Plugin#32]
When I go to the category Spotty -> Artists -> Artist-Name -> 
It only shows Top-Title / Songs / Artist-Radio but not Albums.

Do I make something wrong here?
Is that the way it's supposed to be?

Thanks for your work.

**Comment by michaelherger** [comment]
Any example artist? This certainly works just fine. 

Please also check your server.log for any hint about what's going on.

**Comment by hismastersvoice** [comment]
Thanks for your fast feedback.
After a fresh installation of the Server and the Plugins everything works fine again.
