### ISSUE TITLE
Spotify connect volume at startup

### ISSUE THREAD

**Issue by installaudio** [michaelherger/Spotty-Plugin#33]
A question regarding volume at first connection of Spotify connect 
I have my players set to 20% volume on startup which works well for me & wife.
From the Spotify app on iPhone when I first go to adjust the volume it jumps to 50% volume even if I start with low volume on the app. 
I am using alsa / pcm volume control. 
how can I get this to not jump to a higher volume when I first adjust from the apps / Spotify connect
Many thanks all

**Comment by michaelherger** [comment]
This unfortunately can't be changed. It's a piece of information I'm sent from Spotify. If you control Spotty using the Spotify app, it'll send us the volume and track changes etc.
