### ISSUE TITLE
Spotty and Sonos/UPnP

### ISSUE THREAD

**Issue by sarumont** [michaelherger/Spotty-Plugin#36]
I've just re-installed LMS (Perl update hosed my old Synology installation, so now it's on a stable machine) and have a newer version of Spotty than I used to (the Spotify Connect stuff is the notable difference I see).

    Logitech Media Server Version: 8.2.0 - 1620630276 @ Mon May 10 09:41:53 CEST 2021
    Spotty (v4.4.9)

I have two players configured:

- a Sonos One, connected via UPnP
- my laptop, using `squeezelite`

First up: playing music from my local library is flawless to both destinations. Playing from Spotty to my laptop is also flawless (so far).

Now...when playing to the Sonos One, it's pretty...spotty (couldn't resist). If I just start playing a playlist or song, nothing happens. Press Play/Pause, nothing. If I seek in the track, it seems to magically start working. I cannot skip to the next track, however. It was advancing to the next track when the current track finished playback, but now it seems to not do so. To sum up - I can only play one song at a time, and I have to seek past `0:00` in that song for it to start playing.

This behavior seems to be present either in Spotify Connect mode or non-Connect mode (Side note - the player shows up in my Spotify app, regardless of whether or not I check the _Don't announce..._ checkbox - another bug, maybe?). I don't see anything interesting in `debug` level logs - only the noisy metadata operations.

Any clues here? My Perl's rusty, but I'm happy to help debug if you have any ideas where to begin investigating. Thanks!

**Comment by michaelherger** [comment]
Hi @sarumont - I'd recommend you post to forums.slimdevices.com, as there's the author of the bridge plugins, too. Most likely this is more of a bridge problem than purely Spotty.

**Comment by michaelherger** [comment]
Wouldn't the Sonos expose itself as a Spotify Connect speaker even without Spotty?

**Comment by sarumont** [comment]
@michaelherger Yes, it does expose itself as a Spotify Connect speaker. My goal, though, is to have LMS as the only interface necessary for playing music in the house. :)

I'll check that forum and see if there is anything I can find there (and report back here). Thanks!

**Comment by michaelherger** [comment]
Spotty's Connect mode isn't very robust... so if you plan to use Spotify Connect, then I'd recommend you stick with Sonos' implementation, rather than rely on Spotty for control using Spotify's app.

**Comment by sarumont** [comment]
I'd honestly rather not use the Connect mode - I was just testing everything to see if I could figure out what was going on. :)
