### ISSUE TITLE
When group names are too long, players don't appear in Spotify Connect

### ISSUE THREAD

**Issue by scelfo** [michaelherger/Spotty-Plugin#4]
If I group together enough players with long names, the group stops appearing in Spotify as a Spotify Connect player.

I was able to reproduce this by creating a group of 6 devices with long names such as "Receiver - Upstairs", "Receiver - Downstairs", "Living Room Speakers" and three other long names. To confirm that it's the length of player names, I tried renaming those to "U", "D", "LR, etc and then I was able to group 10 devices and have the group show up in Spotify as a Spotify Connect device.

I didn't iterate on my test to try to narrow in on the limit for the length of the group. Does this sound like something you've seen before? For now I can get by with short device names in LMS but it would be a better experience if Spotty simply truncated the group names. On my iPhone, Spotify seems to only show ~35 characters before it truncates in the UI with "...". Could that truncation be done automatically in Spotty when composing the group name?

**Comment by michaelherger** [comment]
Good catch! I guess it's some 64 bytes limitation somewhere - longer names make a player disappear. I'll fix that.
