### ISSUE TITLE
Spotty binary using 100% System Resources on x86 64 Bit System after Update 1.0.0

### ISSUE THREAD

**Issue by andreasbehnke** [michaelherger/Spotty-Plugin#41]
Looks like after this update spotty helper binary is using 100% system performance:
- Boot --> ok
- Start Streaming via Spottify Connect --> Streaming works very well, but 100% CPU usage
- Start streaming by using new LMS library --> all ok, no heavy CPU usage

**Comment by andreasbehnke** [comment]
@michaelherger  Where can I find an older binary version to test if my problem relates to the 1.0.0 update?

**Comment by michaelherger** [comment]
What platform? What OS?

Can you check your process list to see what exact process is using the CPU? There might be multiple instances of spotty running, using different command line arguments.

**Comment by sbrown7792** [comment]
Hi @michaelherger, I've seen the same issue and can provide some information on my platform.
It's Ubuntu 20.04.2 LTS running on ESXi 6.5.0U3, the VM is allocated 2CPU and 8GB RAM. 
Platform info, player setting, and Spotty advanced settings: https://imgur.com/a/jRTa2sO


Steps taken: 
1. Reboot VM
2. Play song from LMS GUI, wait a few seconds, take reading from linux 'top'
3. Pause song in GUI. 
4. Connect to player via spotify app (windows), play same song. Wait a few seconds, and take reading from linux 'top'

While playing a song selected from LMS, CPU is 'normal':
```
user@squeezebox-server:~$ uptime
 22:32:12 up 4 min,  1 user,  load average: 0.22, 0.24, 0.11
user@squeezebox-server:~$ uname -a
Linux squeezebox-server 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
user@squeezebox-server:~$ top -wcbn 1 | grep -v grep | grep -E 'PID|spotty|squeeze'
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
    813 avahi     20   0    8832   3864   3508 S   0.0   0.0   0:00.02 avahi-daemon: running [squeezebox-server.local]
   1003 squeeze+  20   0  235424 190792  15468 S   0.0   2.3   0:04.68 /usr/bin/perl /usr/sbin/squeezeboxserver --prefsdir /var/lib/squeezeboxserver/prefs --logdir /var/log/squeezeboxserver/ --cachedir /var/lib/squeezeboxserver/cache --charset utf8
   1213 squeeze+  20   0    8824   3336   3176 S   0.0   0.0   0:00.01 /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/Spotty/Bin/i386-linux/spotty-x86_64 -c /var/lib/squeezeboxserver/cache/spotty/b827ebd351a5 -n Wall --disable-audio-cache --bitrate 96 --player-mac b8:27:eb:d3:51:a5 --lms 192.168.250.250:9000
```

While playing the same song, but "casted" from a Spotify client, the process goes to 100% of a single CPU:
```
user@squeezebox-server:~$ top -wcbn 1 | grep -v grep | grep -E 'PID|spotty|squeeze'
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   1213 squeeze+  20   0    9548   4076   3276 S 100.0   0.0   0:06.70 /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/Spotty/Bin/i386-linux/spotty-x86_64 -c /var/lib/squeezeboxserver/cache/spotty/b827ebd351a5 -n Wall --disable-audio-cache --bitrate 96 --player-mac b8:27:eb:d3:51:a5 --lms 192.168.250.250:9000
   1003 squeeze+  20   0  235424 190792  15468 S   6.2   2.3   0:05.36 /usr/bin/perl /usr/sbin/squeezeboxserver --prefsdir /var/lib/squeezeboxserver/prefs --logdir /var/log/squeezeboxserver/ --cachedir /var/lib/squeezeboxserver/cache --charset utf8
    813 avahi     20   0    8832   3864   3508 S   0.0   0.0   0:00.02 avahi-daemon: running [squeezebox-server.local]
```

If I *don't* wait a few second before checking `top`, then I can temporarily see this command. It's usually only present for a few seconds, and doesn't seem to ever have a high CPU usage:
```
1279 squeeze+  20   0   10348   4820   3472 S   0.0   0.1   0:00.71 /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/Spotty/Bin/i386-linux/spotty-x86_64 -n Squeezebox -c /var/lib/squeezeboxserver/cache/spotty/5461d835 --single-track spotify://track:5wjRblZq8DCt5eMoAU1oXv --bitrate 320 --disable-discovery --disable-audio-cache --pass-through
```

If I pause the song from the Spotify app, the original process **immediately** goes back to 0% CPU.

Also also of note, while the command-line shows `--bitrate 96`, the setting does specify 320kbps, and the LMS GUI also seems to indicate this: `320k VBR, Ogg Vorbis (Spotify)`

Let me know if I can get any more info for you.

**Comment by michaelherger** [comment]
Wow... I can easily reproduce this on my dev machine (Mac) too. As soon as I start to play back music via the Spotify app the CPU goes up. I'll look into this. Thanks!

**Comment by andreasbehnke** [comment]
This is my workaround for this issue on a linux x86_64 server:
Fetch older, good working version of bineary.
After an update of spotty plugin, run:

cd /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/Spotty/Bin/i386-linux
mv spotty-x86_64 spotty-x86_64_bak
wget https://github.com/michaelherger/Spotty-Plugin/raw/8927261a6f536e76c8c1cf7d37923f2b4f1f454b/Bin/i386-linux/spotty-x86_64
chown squeezeboxserver:nogroup spotty-x86_64
chmod +x spotty-x86_64
reboot

**Comment by sbrown7792** [comment]
@michaelherger Thanks for fixing this :) Running spotty-helper 1.2.0 and looks like this commit 
[this commit](https://github.com/michaelherger/librespot/commit/ab62fbef7f3c656a7ce671f82622937019d0a9c1) in librespot worked, however ugly you may think it is ;)

**Comment by michaelherger** [comment]
Thanks for the feedback! I was actually looking for this bug report, but looked in the wrong place...
