### ISSUE TITLE
Spotty ain't working on lms

### ISSUE THREAD

**Issue by Jerlag01** [michaelherger/Spotty-Plugin#43]
Hi, I'm running Logitech Media Server version 8.1.1 on Ubuntu 20.04 LTS

Somehow my spotify connection isn't working properly, it says failed to get access token and when I disable the asynchronous token refresh call it just times out.

Logs say this:

[21-07-22 20:51:23.7829] Slim::Networking::IO::Select::__ANON__ (130) Error: Select task failed calling Slim::Web::HTTP::processHTTP: Can't use string ("   0:  0x82ef7e1 - 
") as a HASH ref while "strict refs" in use at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/Spotty/API/Token.pm line 141.
; fh=Slim::Web::HTTP::ClientConn=GLOB(0x564fded11298)

**Comment by michaelherger** [comment]
I’ll need more information, eg. the full log.
