### ISSUE TITLE
[Feature Request] Philips Hue + Spotify (Spotty)

### ISSUE THREAD

**Issue by dekoenpi** [michaelherger/Spotty-Plugin#47]
Hi Michael,

vorab vielen Dank für deine Mühen deiner ganzen Plugins!
Wäre es möglich wenn man direkt von Squeezelite / LMS via Spotty Musik hört die Integration zu nutzen?
Im Moment geht das nur z.B. über die App via Smartphone.

Viele Grüße!

**Comment by michaelherger** [comment]
Die Pressemitteilung sagt:

> Mit Philips Hue + Spotify analysiert die Hue App die Metadaten für jeden Spotify-Song in Echtzeit.

Da das also über die Hue App auf dem Telefon läuft ist da wohl nichts zu machen.

https://hueblog.de/2021/09/01/philips-hue-und-spotify-verbinden-licht-und-musik/

**Comment by dekoenpi** [comment]
Ok. Wenn ich es via Spotify Webbrowser an den LMS vom piCorePlayer sende, erkennt es die Hue App auch.
Vermute in dem Fall das es nicht klappt, da man ja keine "native" Spotify App direkt in LMS hat?

**Comment by michaelherger** [comment]
Wenn du Spotty über LMS steuerst, dann bekommt Spotify davon nicht viel mit. Wenn du aber den "Connect" Modus verwendest, also über ein Spotify UI steuerst, dann läuft die Steuerung komplett über Spotify. Ich nehme an, dass da Hue dann einhängen kann.

**Comment by dekoenpi** [comment]
Danke dir.
