### ISSUE TITLE
Too much default logging

### ISSUE THREAD

**Issue by RichieB2B** [michaelherger/Spotty-Plugin#48]
Spotty is incredibly chatty at the INFOLOG level. For example [DaemonManager.pm](https://github.com/michaelherger/Spotty-Plugin/blob/master/Connect/DaemonManager.pm) 
This is logged to `journald` and `/var/log/daemon.log`
Using `--noinfolog` in `/etc/default/logitechmediaserver` did not help:
```
squeeze+ 1136226  0.3  0.4 314412 265128 ?       Ss   19:59   0:24 /usr/bin/perl /usr/sbin/squeezeboxserver --prefsdir /var/lib/squeezeboxserver/prefs --logdir /var/log/squeezeboxserver/ --cachedir /var/lib/squeezeboxserver/cache --charset utf8 --noinfolog
```
Still gives:
```
Nov 04 19:59:52 nasty systemd[1]: Started Logitech Media Server.
Nov 04 19:59:53 nasty squeezeboxserver[1136226]: [21-11-04 19:59:52.7831] main::init (390) Starting Logitech Media Server (v8.3.0, 1635857800, Tue Nov  2 15:14:58 CET 2021) perl 
Nov 04 19:59:59 nasty squeezeboxserver[1136226]: [21-11-04 19:59:54.6202] Slim::Web::Cometd::handler (421) errorNeedsClient: 10.1.2.3, 00:04:20:2c:xx:xx, status, -, 10, menu
Nov 04 20:03:53 nasty squeezeboxserver[1148211]: [21-11-04 20:03:53.8284] main::main (206) Starting Logitech Media Server scanner (v8.3.0, 1635857800, Tue Nov  2 15:14:58 CET 202
Nov 04 20:03:54 nasty squeezeboxserver[1148211]: [21-11-04 20:03:54.2041] Slim::Music::Import::runImporter (578) Starting Plugins::Spotty::Importer scan
Nov 04 20:03:54 nasty squeezeboxserver[1148211]: [21-11-04 20:03:54.2064] Plugins::Spotty::Importer::scanAlbums (106) Reading albums...
Nov 04 20:03:54 nasty squeezeboxserver[1148211]: [21-11-04 20:03:54.2093] Plugins::Spotty::Helper::_findBin (192) Trying helper application: /var/lib/squeezeboxserver/cache/Insta
Nov 04 20:03:54 nasty squeezeboxserver[1148211]: [21-11-04 20:03:54.2154] Plugins::Spotty::Helper::helperCheck (118) Found helper capabilities table: do {
```
etc

**Comment by michaelherger** [comment]
The default log level is `warn` (see https://github.com/michaelherger/Spotty-Plugin/blob/252d9c55d15944c2e0db319ec906d08f4c4bbe58/Plugin.pm#L27). Just reset the logging to suppress the log statements (see Settings/Advanced/Protocol in the LMS web UI).

**Comment by RichieB2B** [comment]
That did not help much. Settings/Advanced/Protocol  in LMS keeps resetting to Info for plugin.spotty. This does make the combination with `--noinfolog` pretty quiet though. Any ideas why the settings might reset itself?

**Comment by RichieB2B** [comment]
I figured it out.. case of bad translation of "save these settings". Working as expected now. Thanks!

**Comment by michaelherger** [comment]
> I figured it out.. case of bad translation of "save these settings". Working as expected now. Thanks!

What language? Would you have a suggestion for a better translation?
