### ISSUE TITLE
Spotify Family - Only 1 smartphone can see LMS device - Synology Docker

### ISSUE THREAD

**Issue by phqzgunsfjror** [michaelherger/Spotty-Plugin#50]
Hi,

I tried a lot and but I am not able to use the same LMS device with multiple smarthphones in Spotify. Only 1 smartphone can see the LMS device in the Spotify app.
Is there a way to make it running?

- I added 2 accounts (both in same family membership)
- I use "Spotify Client ID" (both accounts are added in the developer portal)
- I only checked "Überwache die Verbindung der Spotty Connect Helferanwendung mit den Spotify Servern. Dies kann helfen, wenn Spotty Connect aktivierte Geräte regelmässig aus den Spotify-Anwendungen verschwinden."

I use: 
- LMS version: 8.2.0 - 1627922070 (via Docker)
- Spotty Plugin version: v4.7.1
- Squeezelite version: v1.9.9-1391-pCP
(but same behavior also in older versions)

Any help would be great :)

**Comment by michaelherger** [comment]
I think you'll have to expose port 5353 UDP from the Docker container. Otherwise discovery won't work.

**Comment by phqzgunsfjror** [comment]
Thanks for your hint.

I am running the docker container on a Synology NAS. It seems the port 5353 UDP is already in usage by avahi-daemon:
```
sudo netstat -tulpn | grep 5353
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           7500/avahi-daemon:
```
I stopped/disabled avahi...
```
sudo synoservice --stop avahi
```
... and I can confirm its not running anymore - even after a restart of the NAS. And the port is not in usage either.
Still same error message that the port is already in usage.

Do you know a workaround?

**Comment by michaelherger** [comment]
Unfortunately no, I'm not too familiar with avahi. But I believe Synology does "reserve" ports using package descriptions. Eg. you couldn't run LMS in  Docker using the same port as the old LMS package, as long as the latter was installed, even if it was shut down.

But there might be some way to tell DSM's avahi to expose Spotty? Don't know...

**Comment by phqzgunsfjror** [comment]
Is it possible to change the port 5353 UDP to something else?

Which thing is actually doing the discovery? Spotify app on the smartphones?

I dont wanna touch avahi. I would rather use MACVLAN in order to assign the Synology a second IP but I havent tested it yet.

**Comment by michaelherger** [comment]
I don't think you can, as this is defined by the service protocol.

**Comment by greinert0s** [comment]
Had the same Problem on a Synology Nas and on a fresh arch linux machine too. To solve the problem I startet the docker in Host mode. After that it workes fine on the arch machine. Didn‘t test it on the Nas yet. 
#Michael:
Thanks a lot for all the work you are doing regarding the lms stuff! Großes Kino!

**Comment by michaelherger** [comment]
Thanks - I'll have to keep the hint about host mode in mind.
