### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by patraff** [michaelherger/Spotty-Plugin#51]
I have just recently attempted install of your plugin on my truenas. When I opened the settings for the plugin it gave the following message;

There has been a problem running the Spotty helper application. Most likely your operating system and/or platform is not supported. Please report the following details to me:

Operating system: freebsd / amd64-freebsd

Helper Applications Folder:
/usr/local/share/logitechmediaserver/Bin
/sbin
/bin
/usr/sbin
/usr/bin
/usr/local/sbin
/usr/local/bin
//bin
/usr/libexec
/var/lib/logitechmediaserver/cache/InstalledPlugins/Plugins/Spotty/Bin
 
Account:	Import:
 
So i guess i'm just following instructions.

**Comment by michaelherger** [comment]
That's correct: I don't build binaries for BSD. You'd have to build it yourself.  I have zero experience with BSD. So the following is just best guesses:

* Install rust (https://freebsd.sh/rust/)
* clone https://github.com/michaelherger/librespot
* run `cargo build --release`
* copy `target/release/spotty` as `spotty-custom` somewhere in your search path (avoid LMS' own paths, as they get replaced during installations)

**Comment by patraff** [comment]
Michael
Thanks for the quick reply. Not being a Linux guru I won't even go there.
Is it best that I set up a spare raspberry pi as the LMS using a basic
Linux compile?
Patrick

**Comment by michaelherger** [comment]
Haha.... TrueNAS isn't even Linux, but FreeBSD based - which is yet another beast.

So yes, if you're happy to run a Pi along with the NAS, then that's the perfect solution IMHO. I've been doing this myself for years. I strongly recommend picoreplayer.org. Easy to set up, well maintained. And as I'm using it myself Spotty will work out of the box 😉.
