### ISSUE TITLE
Spotty Plugin to LMS has been spotty since yesterday

### ISSUE THREAD

**Issue by Softwaremaker** [michaelherger/Spotty-Plugin#52]
Been using the awesome Spotty Plugin to LMS for a few years now and all have been good - till recently.

Connection has been spotty since yesterday. Can login to Spotify, browse everything. When playing a Spotify song on LMS through Logitech DUET, Touch, it plays for a good 7 seconds and then it stops - and it wont play again. Can skip to next song and it will be the same - plays for a good 7 seconds and then it stops. At some devices, it says Buffering but it will remain always at 0%

I am NOT using the Spotty Connect Mode.

Logitech Media Server Version: 7.7.6 - 1452060463
Using Spotty 4.5.4

![SpottyPlugIn](https://user-images.githubusercontent.com/1997252/151088155-f5fded2b-059d-41e4-b4ff-b2d590881c5d.JPG)

**Comment by michaelherger** [comment]
Both your LMS and Spotty plugin installation are outdated. Please bring them up to date.

**Comment by Softwaremaker** [comment]
Thanks Michael for the awesome plugin and reply.

Unfortunately, I am not able to bring LMS up to date. Long story short. It is part of the Synology NAS packages and this is the last supported version because of Perl updates.

Any chance I can update Spotty instead ? Not sure how to do this - looking forward to your advice. Thanks !

**Comment by michaelherger** [comment]
Spotty updates should be available from LMS Settings/Plugins.

Did you check your server.log for hints about the failure to play back? I see you didn't add your own client ID in the Spotty settings. This can cause problems, too. You'd see this in server.log if there were warnings about code 429.

**Comment by Softwaremaker** [comment]
No, I have never seen an error code 429. I am not sure if the recent Synology NAS updates caused some problems. Will rollback and check it out. Thanks Michael

**Comment by Softwaremaker** [comment]
Hi Michael,
IN my current dated version of LMS, the Spotty plugin in 4.5.4. How do I upgrade it manually - if there is a need ?

OR I cannot as 4.5.4 is the latest for my current LMS ?

Thanks !

**Comment by michaelherger** [comment]
Why would you want to update manually? Would LMS not offer the update?

**Comment by Softwaremaker** [comment]
The latest Spotty plugin LMS offers is 4.5.4. I know I cannot update update my current LMS due to reasons above (on Synology NAS) - hence I am asking if I can do the Spotty update to a higher version manually.

**Comment by michaelherger** [comment]
Oh, the SSL certs issue. I guess that's the end for LMS on the DS. You should consider running LMS on a Pi (using eg. picoreplayer.org). Even if you were able to update the plugin, more and more connections will fail, as some certificates expired a few weeks/months ago. And as servers are updating you'll no longer be able to connect to them. You'd need to upgrade your Perl version - which isn't an option on the DS.

**Comment by Softwaremaker** [comment]
Yeah - spot on Michael (and why wouldnt you be ? :) )

Been working and enjoying this mode for a few years now and blocked my PERL update as well so all good. 

Connections are just spotty recently ( ;) ) - meaning it works OK some time and then at other times, it will just stop after 7 seconds. My old logitech devices says buffering and stays at 0%.

I just reinstalled the old Spotty package on LMS again and will test it again. If this doesnt work, I may go the Docker on Synology NAS route. I note the Pi route but I need lesser devices - not more :) I just recently move out of Pi so I dont want to go back there again :)

**Comment by michaelherger** [comment]
May I ask you where about you're living? I've seen multiple similar reports recently.

**Comment by Softwaremaker** [comment]
Singapore

**Comment by Softwaremaker** [comment]
Hi Michael,
The above problem I described seems to have gone away after I deleted/installed the Spotty Plugin on LMS/DSM again. Streamed the entire morning and it has not dropped.

Not sure why and how it happened but its good for now. Thanks for your help and support wit this. Will close this for now.

Thank you very much !

**Comment by michaelherger** [comment]
Thanks for following up. Issues which suddenly show up often disappear as quickly as they came 😀 .

> Singapore

Interesting. The other two reporters of what I consider the same behaviour were in Malaysia and Australia. Considering there must be many times more users in Europe or the US, and none complained, I tend to believe there was a "regional" problem. 🤞🏻
