### ISSUE TITLE
Spotty doesn't play anymore

### ISSUE THREAD

**Issue by ThomasBPG** [michaelherger/Spotty-Plugin#56]
Hello,

I've been using LMS and Spotty for many years, but for the last week or so, it stopped working. If - as an example - I start a playlist in the web UI it attempts to play the first 2-3 secs, but then skips to the next song with the same attempt on 2-3 secs before moving on to next track. There's nothing being played at all.
If I start anything via Spotify Connect via for instance the Android app and select one of the players, it has exactly the same behaviour. 

OS for LMS is Ubuntu 20.04.3 LTS and I run LMS with https://hub.docker.com/r/lmscommunity/logitechmediaserver in the latest release:
Logitech Media Server Version: 8.2.0 - 1627922070 @ Tue Aug 3 11:43:55 CEST 2021
Hostname: baf92401891f
Server IP Address: 172.17.0.3
Server HTTP Port Number: 9000
Operating system: Debian (Docker) - EN - utf8
Platform Architecture: x86_64-linux
Perl Version: 5.32.1 - x86_64-linux-gnu-thread-multi
Audio::Scan: 1.02
IO::Socket::SSL: 2.069
Database Version: DBD::SQLite 1.58 (sqlite 3.22.0)
Total Players Recognized: 3

The players are:
Player Model: SqueezeLite
Player Type: squeezelite
Firmware: v1.9.9-1391-pCP
(all based on piCorePlayer v8.1.0 | www v00017 | linux 5.10.77-pcpCore-v8 (64) | piCore v13.1 | Squeezelite v1.9.9-1391-pCP)

I've increased the log to debug for plugin.spotty and attached it to this issue. Bitrate is set to low, 96k, this is not the normal setting I use, but used for the testing (didn't change any behaviour). In the very end of the log, you will see me try to play a playlist named "Test playlist1" only containing track spotify://track:06aFFobYGQNlyqXcEmYPSm.

Hope I provided enough information, else please don't hesitate to request it.

Thank you for a great plugin that has prolonged my setup for many years !

[server.log.zip](https://github.com/michaelherger/Spotty-Plugin/files/8190299/server.log.zip)

**Comment by michaelherger** [comment]
Please see https://github.com/librespot-org/librespot/issues/972. There are (temporary) workarounds presented there.

**Comment by ThomasBPG** [comment]
Awesome, yes - that did the trick! Thanks for extremely quick response!
