### ISSUE TITLE
Track 'glitch' when skipping forward

### ISSUE THREAD

**Issue by a13xmay** [michaelherger/Spotty-Plugin#57]
When I skip forward a track I'm hearing a tiny snip of the song (further in the song than I've already heard) when skipping forward before the next track starts, like perhaps part of a buffer. Is this normal/expected behaviour?

This appears when browsing music added via web interface.

LMS 8.2 with squeezelite 1.9.9.
Operating system: Debian - EN - utf8
Platform Architecture: i686-linux
Perl Version: 5.20.2 - i586-linux-gnu-thread-multi-64int

**Comment by michaelherger** [comment]
Not expected behaviour, of course. What Spotty helper version are you using (see Spotty settings)? What format are you streaming (see SPT -> xxx transcoding rules in Settings/Advanced/File Types)? Would the problem persist if you changed the latter?

**Comment by a13xmay** [comment]
It's showing 320kbps/Ogg Vorbis, should it be converting? In File Types at the top it says 
"Required binary was not found: spotty-ogg for spt-ogg-*-*"

Helper: /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/Spotty/Bin/i386-linux/spotty (v1.2.0)

**Comment by michaelherger** [comment]
Yes, please give it a try.

**Comment by michaelherger** [comment]
Can I close this issue?

**Comment by a13xmay** [comment]
All adjusted on File Types.
