### ISSUE TITLE
Spotty tracks are shown as URL in Albums and Playlists when added to favorites

### ISSUE THREAD

**Issue by Mrpink200** [michaelherger/Spotty-Plugin#61]
Hi Michael.

I guess i found a bug 
I was playing with your great LMS plugin and had the idea to add some playlists / and or / albums to LMS favorites (as it is allowed).
I found that the result was that the track information were shown as urls and not the track names.
Are you aware of this ?

here 2 examples : one with a playlist , one with an album
i use the skin material on iphone, but it iw the same with standard LMS skin on desktop
![Image](https://user-images.githubusercontent.com/7417251/111474825-bdf20e00-872c-11eb-8082-8c7433b27be4.png)
![Image-1](https://user-images.githubusercontent.com/7417251/111474842-c3e7ef00-872c-11eb-9b96-e3e317a95fd9.png)
![Image-2](https://user-images.githubusercontent.com/7417251/111474854-c6e2df80-872c-11eb-8909-896e4222808e.png)

**Comment by michaelherger** [comment]
Can you please give the latest 8.4 another try. This seems to be working now.

**Comment by Mrpink200** [comment]
Hello Michael. Unfortunately i have quit using lms for plexamp. I cannot test

**Comment by michaelherger** [comment]
Ok, no problem. I'll consider this done 😁
