### ISSUE TITLE
Only the current song is in spotty visible

### ISSUE THREAD

**Issue by BatmanN8** [michaelherger/Spotty-Plugin#64]
If I use spotty connect and select an album in the spotify app only the current song is visible in LMS. All songs are visible in the spotify app. controle e.g. next song is not possible via lms. is it possible to transfer the queue from spotify to spotty/lms?

**Comment by michaelherger** [comment]
Unfortunately the Spotify API doesn't give enough context to "transfer" the playlist. Eg. for albums or playlists the API wouldn't give me information about what album or playlist was playing, only the current track.

**Comment by BatmanN8** [comment]
Pity! Thanks for the quick reply

**Comment by michaelherger** [comment]
If you're on Android: there's an app LMS Connect which allows you to play pretty much anything in LMS through the sharing sheet (or whatever it's called). 

https://forums.slimdevices.com/showthread.php?114611-Announce-LMS-Connect-streaming-Tidal-Qobuz-to-LMS-via-native-Android-apps
