### ISSUE TITLE
LMS - Spotty plugin no longer visible in plug-in list

### ISSUE THREAD

**Issue by DSew20** [michaelherger/Spotty-Plugin#65]
Hello - like a few others, spotty stopped working recently.

I read in a forum that disabling then enabling can sometimes fix the issue.  Except, after disabling I am unable to see spotty in the list of plugins.

Any ideas how to get the plug-in to show and how to then fix the recent issue with spotify tokens?

**Comment by michaelherger** [comment]
Sounds like a networking problem of your LMS. Please check its server.log and report back.

**Comment by DSew20** [comment]
Hello.  I think this was a DNS issue.  Resolved, and not working ok.
