### ISSUE TITLE
Search for songs returns mixed in random results

### ISSUE THREAD

**Issue by NeilSargent** [michaelherger/Spotty-Plugin#67]
The search function does not have a separate Songs list, like Spotify. The results in the main list contain 10-20% random results not matching the search criteria in any way
![Capture](https://user-images.githubusercontent.com/70237178/179078997-37d7dba0-0e40-4425-9338-57c46c729c1b.PNG)
.

**Comment by michaelherger** [comment]
The search function uses Spotify's API. If they return irrelevant results, then that's what you'll get.

https://developer.spotify.com/console/search/
