### ISSUE TITLE
Spotty Spotify für Squeezebox not running on my Synology NAS

### ISSUE THREAD

**Issue by cheimlicher** [michaelherger/Spotty-Plugin#72]
Hello Michael

I tried to run the Spotty Spotify für Squeezebox Plugin (v4.8.3) on my (quit old) NAS. It did not work, but showed the following error message: 

Beim Ausführen der Spotty Helfer-Anwendung ist ein Fehler aufgetreten. Vermutlich wird diese auf ihrem System nicht unterstützt. Bitte wenden Sie sich an mich, unter Angabe der folgenden Plattform-Informationen:

Betriebssystem: Synology DSM 6.2.4 / armle-linux

Ordner für Hilfsprogramme:
/volume1/@appstore/SqueezeCenter/Bin
/sbin
/bin
/usr/sbin
/usr/bin
/usr/syno/sbin
/usr/syno/bin
/usr/local/sbin
/usr/local/bin
/usr/libexec
/volume1/@appstore/SqueezeCenter/Cache/InstalledPlugins/Plugins/Spotty/Bin/arm-linux
/volume1/@appstore/SqueezeCenter/Cache/InstalledPlugins/Plugins/Spotty/Bin
sh: ldd: command not found

Can you help me? Maybe I need only the right helper application, but in the list I only find the following entries: 

![image](https://user-images.githubusercontent.com/60394685/186256266-a9f485c1-8bd7-4dd3-bc2e-fb1c3a9dfd40.png)

Besten Dank und liebe Grüsse
Christian

**Comment by michaelherger** [comment]
You _could_ try the "Pi Zero" or "Legacy" helpers. But I'd rather recommend you find an alternative way to run LMS. You shouldn't stick with the outdated DSM longer term. It might put your data at risk. But you can't upgrade DSM, or LMS would break.

My preferred suggestion in this situation is to get a Raspberry Pi and picoreplayer.org to run LMS, while keeping the music files on the NAS. Even a Pi 3 might be much faster running LMS than your NAS alone.

**Comment by cheimlicher** [comment]
I tried your suggestion, bought a Raspberry Pi and installed piCorePlayer with LMS. The spotty plugin now works perfectly, thank you very much.
