### ISSUE TITLE
Skip to the next song after 8-10 minutes.

### ISSUE THREAD

**Issue by orz-t** [michaelherger/Spotty-Plugin#74]
I play a song longer than 10 minutes, it automatically skips to the next song after about 8 to 10 minutes during playback.

Check the spotify log, the following log is recorded during playback, and after about 10 seconds, it skips to the next song.

`[22-09-25 22:54:35.0327] Plugins::Spotty::Plugin::updateTranscodingTable (270) [spotty.exe] --ap-port=12321  -n Squeezebox -c "C:\ProgramData\Squeezebox\Cache\spotty\e4bf24a8" --single-track $URL$ --bitrate 320 --disable-discovery --disable-audio-cache --pass-through $START$
[22-09-25 22:54:35.0345] Plugins::Spotty::Plugin::updateTranscodingTable (270) [spotty.exe] --ap-port=12321  -n Squeezebox -c "C:\ProgramData\Squeezebox\Cache\spotty\e4bf24a8" --single-track $URL$ --bitrate 320 --disable-discovery --disable-audio-cache $START$
[22-09-25 22:54:35.0353] Plugins::Spotty::Plugin::updateTranscodingTable (270) [spotty.exe] --ap-port=12321  -n Squeezebox -c "C:\ProgramData\Squeezebox\Cache\spotty\e4bf24a8" --single-track $URL$ --bitrate 320 --disable-discovery --disable-audio-cache $START$ | [flac] -cs --channels=2 --sample-rate=44100 --bps=16 --endian=little --sign=signed --fast --totally-silent --ignore-chunk-sizes -
[22-09-25 22:54:35.0360] Plugins::Spotty::Plugin::updateTranscodingTable (270) [spotty.exe] --ap-port=12321  -n Squeezebox -c "C:\ProgramData\Squeezebox\Cache\spotty\e4bf24a8" --single-track $URL$ --bitrate 320 --disable-discovery --disable-audio-cache $START$ | [lame] -r --silent -q $QUALITY$ $BITRATE$ - -`

Why is this being logged in the middle of playback?

Operating environment.
OS: Windows 10
LMS Version: 8.2.0
Spotty Version: 4.8.4
Perl Version: 5.14.1 - MSWin32-x86-multi-thread

**Comment by michaelherger** [comment]
Would you mind sharing your full server.log.zip? Feel free to upload to https://www.dropbox.com/request/T3RctyzGgNg0oFDubq6a. The above line is only a symptom of the problem. Would you mind giving the 8.3 nightly build another try?

https://downloads.slimdevices.com/nightly/?ver=8.3

**Comment by orz-t** [comment]
Thanks for your advice.

I saved the log file to dropbox.
File name: orz-t_server.log

I'll try the 8.3 nightly build now.

**Comment by orz-t** [comment]
8.3 nightly build had the same result.
I saved the log to dropbox.
File name: orz-t_server_8.3.log

**Comment by michaelherger** [comment]
I don't see anything special in these log files. What format option are you using? Please check Settings/Advanced/File Types: there are options to stream "Spotty" to either Ogg, FLAC, PCM, MP3 etc. Please disable Spotty -> Ogg and give it another try.

**Comment by orz-t** [comment]
I already disabled the Spotty Ogg format option. Only FLAC is set to spotty/flac.
I use LMS/Spotty for playback, but it skips even when using Spotify Connect.

**Comment by michaelherger** [comment]
Did you disable Ogg _after_ experiencing the problems? What if you re-enabled it? Or PCM? Basically: can you double check you get the same behavior, no matter what conversion you use?

**Comment by orz-t** [comment]
I've checked the ogg option and it causes problems both enabled and disabled. At this time FLAC is set to spotty/flac. PCM and MP3 are unconfirmed, so I will check later.

**Comment by orz-t** [comment]
I haven't finished checking yet, but I have one question.
Spotify playback by spotty seems to buffer one song at the start of playback. If playback skips in the middle, is it possible that buffering is failing? Is there a way to log buffering failures or a confirmation method?

**Comment by michaelherger** [comment]
I fear that the failure is somewhere in the external (to LMS) pipeline using spotty.exe. I wouldn't know how to catch this.

Did you enable any of the streaming method options in Settings/Advanced/Networking?

**Comment by orz-t** [comment]
As a result of trying some settings, only FLAC of the file type Spotty is spotty.exe/flac, and all others are disabled, and playback is no longer skipped. In addition, even if only PCM is spotty.exe and everything else is disabled, playback will not be skipped. In addition, the setting of Streaming mode for HTTP(S) of the network is persistent mode. 

Spotty had done nothing wrong. Sorry for the inconvenience.

**Comment by michaelherger** [comment]
Thanks for sharing your findings! Can you confirm:

* force SPT -> FLAC
* use "persistent" mode for the streaming

**Comment by michaelherger** [comment]
Closing lack of response.
