### ISSUE TITLE
Spotify Favorites? Edit: Liked Songs

### ISSUE THREAD

**Issue by grendelrt** [michaelherger/Spotty-Plugin#80]
Cant seem to my find songs that I tagged as favorites in Spotify anywhere, figured they would be under playlists. Sorry if this is a stupid question....I tried searching for favorites in the issues.

**Comment by michaelherger** [comment]
Did you create your own Client ID as outlined in the Spotty settings?

**Comment by grendelrt** [comment]
Gave that a shot now, created the clientID and added it, restarted LMS. I see all my Spotify playlists in the playlist section, but no "Favorites" there or in favorites section on LMS. Where should the favorites playlist show up? Thanks for the help :)

**Comment by michaelherger** [comment]
In your personal section with your albums, artists etc. there should be an item "Songs". I personally never use it, as I consider a long, flat list of tracks utterly useless.

**Comment by grendelrt** [comment]
I don't seem to have a songs item, its ok, not a big deal lol. 
![Screenshot 2023-02-07 164730](https://user-images.githubusercontent.com/42378882/217374412-69e0bb63-00e0-40ac-ad7e-76edb08f8e33.png)
![Screenshot 2023-02-07 164747](https://user-images.githubusercontent.com/42378882/217374415-49befbb4-24a4-48e5-9a4c-513dcdea11d3.png)

**Comment by michaelherger** [comment]
It would be in the Spotty menus, not the main My Music section.

**Comment by grendelrt** [comment]
Ahh maybe that's my problem, I had clicked on Spotty  and I get this loading arrow and it then says empty. But when I look in my music normal, I am seeing and can play spotify albums. 
![Screenshot 2023-02-07 172919](https://user-images.githubusercontent.com/42378882/217381272-99afd01c-d358-412d-84b1-0d60fc751817.png)
![Screenshot 2023-02-07 173100](https://user-images.githubusercontent.com/42378882/217381518-3f879ba9-8157-4f5a-9bed-71d832926db2.png)

**Comment by michaelherger** [comment]
Please check your server.log for any hint about the failure to load the menu.

**Comment by grendelrt** [comment]
Well, I went scorched earth and deleted the plug in and reloaded it and everything is there now when I click the Spotty section. Sorry for troubling you, something must have gotten hung up at some point. Thanks for your patience and awesome plugin!
