### ISSUE TITLE
Artist View Problem

### ISSUE THREAD

**Issue by toyoman** [michaelherger/Spotty-Plugin#83]
with Version 4.8.7 I have a problem with the Artist View in the Spotty Application. I see only 700 Artists and they are all to see 14 times. for example: 14x ABBA. I already restartet and did a re-search of all music.

**Comment by michaelherger** [comment]
Can you please enable debug logging for plugin.spotty, then re-do whatever you did to get that list. Then disable the logging again and send me the resulting server.log.zip file (Settings/Advanced/Logging).

https://www.dropbox.com/request/T3RctyzGgNg0oFDubq6a

**Comment by toyoman** [comment]
> Can you please enable debug logging for plugin.spotty, then re-do whatever you did to get that list. Then disable the logging again and send me the resulting server.log.zip file (Settings/Advanced/Logging).
> 
> https://www.dropbox.com/request/T3RctyzGgNg0oFDubq6a

how can I enable debug loggin for plugin.spotty?

**Comment by toyoman** [comment]
> > Can you please enable debug logging for plugin.spotty, then re-do whatever you did to get that list. Then disable the logging again and send me the resulting server.log.zip file (Settings/Advanced/Logging).
> > https://www.dropbox.com/request/T3RctyzGgNg0oFDubq6a
> 
> how can I enable debug loggin for plugin.spotty?

OK, i found it... one moment

**Comment by toyoman** [comment]
Ok, i sent the logfile to you (dropbox)

**Comment by michaelherger** [comment]
Ok, something's wrong there... don't know whether this is the plugin or the Spotify service: it seems to ignore the `offset` parameter. Thus it's always sending the same 50 items, for each request. And as you have 656 artists, it would do 14 requests, receiving 50 results each time. Which causes ABBA to be listed 14x etc.

I'll look into this. Thanks for the heads up!

**Comment by michaelherger** [comment]
Oh, we are not alone: https://community.spotify.com/t5/Spotify-for-Developers/Problems-with-quot-Get-Followed-Artists-quot-API-getting-next/td-p/5513680. They seem to have changed the API. It's no longer using pages and offsets, but you have to pass the last artist ID from the previous request's result as a parameter... which sucks big time, as we now have to wait for each response before we can fetch more. This will _massively_ slow down browsing artists. Ugh...

**Comment by toyoman** [comment]
Thanks for investigating! I love your work and the spotty plugin. Hope you will find a good solution ;-)

**Comment by michaelherger** [comment]
Seems to be working again. As of a few minutes ago I now get working data again.

**Comment by toyoman** [comment]
I can confirm, it works now again.
