### ISSUE TITLE
picoreplayer-slimserver-lms spotty 4.8.8 playing spotify playlist from lms favorites doesn't work anymore.

### ISSUE THREAD

**Issue by ajuga2** [michaelherger/Spotty-Plugin#84]
When trying to play a playlist from lms favorites (spotify:playlist:.... in favorites.opml) it returns an empty playlist. Playing a single track from lms favorites (spotify://track:.... in favorites.opml) works.
When trying to play the same playlist via de spotty app (via my apps) works however.
Deleting /mnt/mmcblk0p2/tce/slimserver/Cache, did not make any difference. It just installed version 4.8.8 again

After 'rolling back' to version 4.8.2 (for no specific reason I choose this one) it worked again. 
- I downloaded zip from https://github.com/Blackfiction/Spotty-Plugin/tree/5456915800df4f9e6bc3f35a61631b7cdd26cf20 and unpacked. Don't know if this is the right way to find an older version
- Stopped lms and replaced all files in /mnt/mmcblk0p2/tce/slimserver/Cache/InstalledPlugins/Plugins/Spotty (made available via a samba share)
- Restarted lms
Again don't know how to install it the right way. But after reboot, it still worked and version 4.8.2 is shown as the active version

**Comment by michaelherger** [comment]
What LMS version are you using? I recently added a patch to 8.4 to improve the use case you describe. And I can play a favourite with a content of `spotify:album:4IUeKh2mYOX2njthGA8STM`. It played correctly when selected from Squeezeplay, Default and Material skins.

**Comment by ajuga2** [comment]
Logitech Media Server Versie: 8.1.1 - 1610364019 @ Thu Jan 14 06:27:45 CET 2021

I don't know about LMS favorite spotify:album:... because I don't use it. I ran into the problem because of LMS favorite spotify:playlist:...

**Comment by michaelherger** [comment]
Your LMS is more than two years old... Don't you have any way to upgrade it? As far as I know the issue you're seeing is not there in recent LMS.

**Comment by ajuga2** [comment]
I guess you mean https://github.com/Logitech/slimserver?

in pCP <ip-adres-of-picoreplayer>/cgi-bin/lms.cgi update LMS gives there is no update? Don't know which url it uses
via <ip-adres-of-picoreplayer>:9000 settings it gives \https://downloads.slimdevices.com/LogitechMediaServer_v8.3.1/logitechmediaserver-8.3.1-noCPAN.tgz

how can I download and neatly install the version in https://github.com/Logitech/slimserver?

**Comment by ajuga2** [comment]
I followed https://docs.picoreplayer.org/how-to/upgrade_lms/ to upgrade to nightly bugfix for laters stable release (Logitech Media Server Versie: 8.3.2 - 1677516824 @ Mon 27 Feb 2023 06:30:31 PM CET)
then updated spotty to 4.8.8 again. It now works again

**Comment by ajuga2** [comment]
After making sure what the development version was I again upgraded to 8.4 following the same guide
(Logitech Media Server Versie: 8.4.0 - 1678519305 @ Sat 11 Mar 2023 09:00:12 AM CET).
