### ISSUE TITLE
Support for Spotify Shows

### ISSUE THREAD

**Issue by pi-rub** [michaelherger/Spotty-Plugin#85]
There is a new audio type in spotify called 'Show' like Simon's Sunday. This type cannot be played on Spotify Connect devices based on spotty plugin and lms. The Spotify Connect devices show "Dieser Song kann nicht abgespielt werden".
Is there any possibility to add the feature to play Shows on Spotify Connect devices?

Thanks!

**Comment by michaelherger** [comment]
This one? https://open.spotify.com/show/2qlt2xFWSBxGaIAcIgALoS?si=76a0fad591a44ac1

I can confirm that it wouldn't play over Connect on Spotty. But neither would it on my Samsung soundbar or TV set or the Apple TV. I can only play it in the Spotify apps on Mac or iPhone:

![Bildschirm­foto 2023-03-22 um 21 50 56](https://user-images.githubusercontent.com/2789989/227035013-a98f130d-1dc4-4825-8909-eb9a203da3a3.png)

Must be a limitation of the show itself. But then I can play it from LMS: just paste the above URL in the "Play Radio URL" input field.
