### ISSUE TITLE
No autoplay on Spotify Connect

### ISSUE THREAD

**Issue by Oinkweil** [michaelherger/Spotty-Plugin#90]
Hi Michael,

I'm using LMS in Docker with the Group Player plugin for multiroom audio (these serve two MoOde Audio Squeezelite players). Spotty works very well in Spotify Connect for single and multiroom, but with the exception that it won't autoplay.

I've tried Spotty:

- with and without Don't Stop The Music installed
- with Spotify Client ID enabled

No joy. 

In Librespot, it's straightforward to set the autoplay flag, but I can't find anything similar in Spotty Helper, or documented. 

Very grateful for any help or investigation.

Kind regards,
David

**Comment by michaelherger** [comment]
Would it work with a single player, without the group plugin?

**Comment by Oinkweil** [comment]
Thanks for your response. Autoplay doesn't work with a single player either.

I'm using Spotty v4.8.8 in LMS 8.3.1 running in Docker on a Pi4B with MoOde Audio 8.3.3 installed (based on RaspiOS 11.7). Helper is v1.3.0.

Kind regards

**Comment by michaelherger** [comment]
And you did enable Autoplay in the Spotify app controlling the player?

**Comment by Oinkweil** [comment]
Yes

**Comment by michaelherger** [comment]
I'm glad we got this sorted. I didn't remember that setting either... so only when I got back to the code today I figured it out 🤦🏻.
