### ISSUE TITLE
Possible to omit Spotty from media library scans?

### ISSUE THREAD

**Issue by eater** [michaelherger/Spotty-Plugin#91]
When I manually rescan my media library (after adding new files), the scan of local media is super quick, but then the scan of Spotty playlists takes hours, and sometimes crashes the LMS instance. Would it be possible for me to run a rescan of local media without including Spotty?

**Comment by michaelherger** [comment]
You can disable the Spotify integration by deactivating the "Online Library Integration" plugin.

**Comment by eater** [comment]
Thanks!
