### ISSUE TITLE
No "Liked Songs" playlist

### ISSUE THREAD

**Issue by lytenyn** [michaelherger/Spotty-Plugin#92]
Thanks for implementing spotty, it's a great addition to LMS.

In spotify, I have a playlist called "Liked Songs". In spotty, I can find all other playlists, but not this one.

This issue seems to be the same as #80, but I cannot understand the solution there.
I cannot find a menu called "Songs" either.

The other issue also mentions creating a client ID, but the documentation for the client ID only says that this helps in case one has issues with rate limiting, which I do not have (I think).

Could you explain again how to find the "Liked Songs" playlist?
If the client ID is required, maybe the help text for that option should be changed?

Thank you!

**Comment by michaelherger** [comment]
Follow the instructions to use your own client ID anyway. It also frees some features which otherwise might cause issues.

**Comment by lytenyn** [comment]
Thank you, this has added the missing playlist. I'm curious which other features have appeared now.
